### ISSUE TITLE
cxn->prpl_conn elimination: Emit signal for login interaction request

### ISSUE THREAD

**Issue by dwmw2** [awslabs/pidgin-chime#2]
We're working on splitting generic Chime code from Purple-specific code, and eliminating all use of the `prpl_conn` member of `ChimeConnection`.

To do this for the login code, we probably want to add a new `auth-requested` signal on the `ChimeConnection` object. Its arguments can be remarkably similar to what we alreadfy pass to `purple_request_fields()` or `purple_request_input()` — title, prompt(s), a boolean field indicating whether we need a username to be provided.

Either we can make it generic enough to also handle `request_consent()`, or we can introduce a different signal for that, or perhaps just assume consent on the basis that if they install a Chime client and enter their password it's a fairly safe bet that they really *did* want to use it... ;)

The purple-side code, after receiving the signal and getting responses from the user, would provide them back to the `ChimeConnection` through a new `purple_connection_provide_auth()` function. Come up with a better name...

**Comment by etanol** [comment]
Five months past my expected target date, I finally submitted #19.  That PR should also fix some recent problems with the Amazon sign in code.
