### ISSUE TITLE
Doesn't link with LDFLAGS="-Wl,--no-undefined -Wl,--as-needed"

### ISSUE THREAD

**Issue by bgmilne** [awslabs/pidgin-chime#23]
When building as follows, there are multiple ```undefined reference to XXX``` errors
```
./autogen.sh && LDFLAGS="-Wl,--no-undefined -Wl,--as-needed" ./configure && make
```

Specifically:
1. libapp-transmitter.la needs $(FARSTREAM_LIBS)
```
make[1]: Entering directory '/home/bgmilne/Downloads/github/pidgin-chime/fs-app-transmitter'
  CCLD     libapp-transmitter.la
.libs/libapp_transmitter_la-fs-app-stream-transmitter.o: In function `fs_app_stream_transmitter_class_init':
/home/bgmilne/Downloads/github/pidgin-chime/fs-app-transmitter/fs-app-stream-transmitter.c:176: undefined reference to `fs_stream_transmitter_get_type'
```

2. libchimeprpl.la needs -ldl
```
  CCLD     libchimeprpl.la
prpl/.libs/libchimeprpl_la-chat.o: In function `select_screen_share':
/home/bgmilne/Downloads/github/pidgin-chime/prpl/chat.c:629: undefined reference to `dlopen'
/home/bgmilne/Downloads/github/pidgin-chime/prpl/chat.c:631: undefined reference to `dlsym'
```

3. The evolution plugin uses functions from libcamel (libcamel-1.2.so in my case)
```
make[1]: Entering directory '/home/bgmilne/Downloads/github/pidgin-chime/evolution-plugin'
  CC       module_event_from_template_la-event-from-template.lo
  CCLD     module-event-from-template.la
.libs/module_event_from_template_la-event-from-template.o: In function `generate_comp':
/home/bgmilne/Downloads/github/pidgin-chime/evolution-plugin/event-from-template.c:233: undefined reference to `camel_internet_address_new'
/home/bgmilne/Downloads/github/pidgin-chime/evolution-plugin/event-from-template.c:234: undefined reference to `camel_address_get_type'
/home/bgmilne/Downloads/github/pidgin-chime/evolution-plugin/event-from-template.c:234: undefined reference to `camel_address_unformat'
```
4. The pidgin plugin uses symbols provided by the pidgin binary, which libtool doesn't seem to pass the correct options to ld for:
```
.libs/chimeseen_la-chimeseen.o: In function `chimeseen_plugin_load':
/home/bgmilne/Downloads/github/pidgin-chime/chimeseen/chimeseen.c:163: undefined reference to `pidgin_conversations_get_handle'
.libs/chimeseen_la-chimeseen.o: In function `conv_seen_cb':
/home/bgmilne/Downloads/github/pidgin-chime/chimeseen/chimeseen.c:95: undefined reference to `gtk_imhtml_get_type'
.libs/chimeseen_la-chimeseen.o: In function `got_convmsg_cb':
/home/bgmilne/Downloads/github/pidgin-chime/chimeseen/chimeseen.c:122: undefined reference to `gtk_imhtml_get_type'
```

While it is not such an issue with plugins, some distributions (e.g. Mageia) apply -Wl,--no-undefined -Wl,--as-needed by default in RPM macros that are plumbed into %configure, in order to avoid unnecessary transitive dependencies. See e.g. [Underlinking issues in packaging](https://wiki.mageia.org/en/Underlinking_issues_in_packaging)

**Comment by dwmw2** [comment]
Can we add `-ldl` unconditionally? At least it needs to go away for Windows, but aren't there some Unix platforms which have `dlopen()` in libc not in a separate library? I think we need a `configure` check for that, don't we?

**Comment by bgmilne** [comment]
Yep, we'll [need a configure check for libdl](https://autotools.io/autoconf/finding.html) for other Unix flavours.

**Comment by bgmilne** [comment]
Moving this discussion from the PR to the issue:

> We can do the camel-1.2 thing slightly more easily by just adding it to the existing list of pkgconfig requirements for the evo plugin, that end up in $(EVOLUTION_LIBS). Fixed; thanks.

I tried that approach first, and it failed for me, because I didn't have a pkg-config file for libcamel, thus I switched to AC_SEARCH_LIBS. I will check again tonight.

> So now we just have the plugin linking? Did you work out how that works for the other Pidgin (not purple) plugins?

I did notice [this](http://svnweb.mageia.org/packages/cauldron/pidgin/current/SPECS/pidgin.spec?revision=1228379&view=markup#l324) in the pidgin package itself.

There are a few other pidgin-* packages, but I am not sure which are actually pidgin UI plugins vs. libpurple plugins, but looking at some other random plugin-based package I am familiar with (e.g. [this one](http://svnweb.mageia.org/packages/cauldron/openldap-check_password/current/SPECS/openldap-check_password.spec?revision=946823&view=markup)), it should be possible.

I will try and conclude this tonight.

**Comment by bgmilne** [comment]
> I tried that approach first, and it failed for me, because I didn't have a pkg-config file for libcamel, thus I switched to AC_SEARCH_LIBS. I will check again tonight.

Well, it works now :-)

> So now we just have the plugin linking? Did you work out how that works for the other Pidgin (not purple) plugins?

I have looked at a few similar packages, and I think most of them aren't trying the same thing, or they don't get -Wl,--no-undefined as LDFLAGS to any plugins.

So, I think this is as good as we can get it for now.
