### ISSUE TITLE
Sharing screen is slow and not always update

### ISSUE THREAD

**Issue by thiagomg** [awslabs/pidgin-chime#32]
Sharing screen is slow and sometimes it takes couple minutes to change. I also noticed that after it starts to change, when it starts, it is very slow.

I am using version 1.1-8 on ubuntu

**Comment by dwmw2** [comment]
Which direction are we talking about? You sharing your own screen, or viewing someone else's?

**Comment by dwmw2** [comment]
I think this is finally fixed — and I've worked out why I could never reproduce it on demand — with
https://github.com/awslabs/pidgin-chime/commit/01995c81bf9f0e5bbe45d6b

**Comment by eli-osherovich** [comment]
2021 and this is still a huge problem.

**Comment by dwmw2** [comment]
Hi @eli-osherovich 

I'm fairly sure it isn't the same problem as before; can you clarify the behaviour you see?

**Comment by eli-osherovich** [comment]
I am not sure this is the same problem or this is the right repository since I use web chime. When one of the users switch slides all the others have a huge delay (> 1m) before they see the change.

**Comment by dwmw2** [comment]
Indeed, this is the open source native Linux client.
