### ISSUE TITLE
Signin broken for AD users

### ISSUE THREAD

**Issue by omnigrok** [awslabs/pidgin-chime#37]
Hiya,

I'm getting an error "Error during corporate authentication setup" when attempting to sign-in.

I've verified the issue is present in master in 130925146e909fa9ab2bc20549e2f2d17c244d2e (current HEAD).

Output of chime-get-token is in [this gist](https://gist.github.com/omnigrok/2bf88f82c086d96ac50c88e85aa117e7).

**Comment by etanol** [comment]
The commit 130925146e909fa9ab2bc20549e2f2d17c244d2e is **not** the current `HEAD`.

You should use 84ed1e56be264a50f33688c3dd8f0a8cb00e02d9 which fixes the last known *WarpDrive* login issues.
