### ISSUE TITLE
Crashes when starting pidgin

### ISSUE THREAD

**Issue by thiagomg** [awslabs/pidgin-chime#40]
When I start pidgin, after receiving all past messages (apparently), pidgin constantly crashes.
The issue seems to be due to an invalid JSON - maybe it gets invalid after some cleaning.

I am attaching a debug log + callstack in debug mode

Lots of this warning was seen:

(Pidgin:19241): Json-CRITICAL **: 10:32:30.001: json_node_get_object: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_OBJECT' failed

Attached files:
* pidgin-issue-debug.txt - I ran export CHIME_DEBUG=2; gdb --args pidgin -d
* pidgin-callstack.txt - I ran gdb pidgin

the chime plugin is compiled with debug enabled. (-O0 -g).

[pidgin-callstack.txt](https://github.com/awslabs/pidgin-chime/files/3698784/pidgin-callstack.txt)
[pidgin-issue-debug.txt](https://github.com/awslabs/pidgin-chime/files/3698785/pidgin-issue-debug.txt)

**Comment by dwmw2** [comment]
This should be fixed with commit a0d4ba4c9dc269ba81801f0f32ff94c026425a87
