### ISSUE TITLE
Installation in Ubuntu

### ISSUE THREAD

**Issue by MarcusRhodes** [awslabs/pidgin-chime#46]
How does one install this in pidgen on Ubuntu 18.04? I tried yum, as dnf doesn't work for Ubuntu, but I got a repo error:
`There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
`
A friend suggested 'apt', but that yielded this:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pkgconfig(purple)
E: Unable to locate package pkgconfig(libsoup-2.4)
E: Couldn't find any package by glob 'pkgconfig(libsoup-2.4)'
E: Couldn't find any package by regex 'pkgconfig(libsoup-2.4)'
E: Unable to locate package pkgconfig(json-glib-1.0)
E: Couldn't find any package by glob 'pkgconfig(json-glib-1.0)'
E: Couldn't find any package by regex 'pkgconfig(json-glib-1.0)'`

**Comment by dwmw2** [comment]
Yeah, `apt` is the tool to use, but Debian/Ubuntu don't have simple ways to install pkg-config dependencies. Instead of, for example, `pkgconfig(gnutls)` you have to manually work out somehow what their *name* for each package is.

There's a PPA at https://launchpad.net/~dwmw2/+archive/ubuntu/pidgin-chime which has prebuilt versions, along with updated Pidgin and the headset plugin for use with USB headsets and voice calls.

If you want to build from source, try:
```
sudo apt-get -y install $(sed -n '/Build-Depends:/,/^$/{s/^.*://;s/[(,].*//;p}' debian/control)
```

**Comment by MarcusRhodes** [comment]
I installed pidgin-chime, but I don't see chime as an option in pidgin. Is there another step I may not have done?

**Comment by dwmw2** [comment]
Restart Pidgin, perhaps? If that doesn't do it, please start run `pidgin -d` and show the output here.

**Comment by MarcusRhodes** [comment]
`Gtk-Message: 12:27:47.812: Failed to load module "canberra-gtk-module"
(12:27:47) prefs: Reading /home/marcus/.purple/prefs.xml
(12:27:47) prefs: Finished reading /home/marcus/.purple/prefs.xml
(12:27:47) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(12:27:47) dbus: okkk
(12:27:47) plugins: probing /usr/lib/pidgin/spellchk.so
(12:27:47) plugins: probing /usr/lib/pidgin/gtkbuddynote.so
(12:27:47) plugins: probing /usr/lib/pidgin/markerline.so
(12:27:47) plugins: probing /usr/lib/pidgin/iconaway.so
(12:27:47) plugins: probing /usr/lib/pidgin/extplacement.so
(12:27:47) plugins: probing /usr/lib/pidgin/gestures.so
(12:27:47) plugins: probing /usr/lib/pidgin/cap.so
(12:27:47) plugins: probing /usr/lib/pidgin/convcolors.so
(12:27:47) plugins: probing /usr/lib/pidgin/history.so
(12:27:47) plugins: probing /usr/lib/pidgin/notify.so
(12:27:47) plugins: probing /usr/lib/pidgin/pidginrc.so
(12:27:47) plugins: probing /usr/lib/pidgin/xmppdisco.so
(12:27:47) plugins: probing /usr/lib/pidgin/ticker.so
(12:27:47) plugins: probing /usr/lib/pidgin/transparency.so
(12:27:47) plugins: probing /usr/lib/pidgin/sendbutton.so
(12:27:47) plugins: probing /usr/lib/pidgin/themeedit.so
(12:27:47) plugins: probing /usr/lib/pidgin/xmppconsole.so
(12:27:47) plugins: probing /usr/lib/pidgin/vvconfig.so
(12:27:47) plugins: probing /usr/lib/pidgin/timestamp_format.so
(12:27:47) plugins: probing /usr/lib/pidgin/timestamp.so
(12:27:47) plugins: probing /usr/lib/pidgin/musicmessaging.so
(12:27:47) plugins: probing /usr/lib/purple-2/dbus-example.so
(12:27:47) plugins: probing /usr/lib/purple-2/newline.so
(12:27:47) plugins: probing /usr/lib/purple-2/libgg.so
(12:27:47) plugins: probing /usr/lib/purple-2/libsimple.so
(12:27:47) plugins: probing /usr/lib/purple-2/psychic.so
(12:27:47) plugins: probing /usr/lib/purple-2/libaim.so
(12:27:47) plugins: probing /usr/lib/purple-2/libsametime.so
(12:27:47) plugins: /usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
(12:27:47) plugins: probing /usr/lib/purple-2/ssl.so
(12:27:47) plugins: probing /usr/lib/purple-2/libbonjour.so
(12:27:47) plugins: probing /usr/lib/purple-2/libirc.so
(12:27:47) plugins: probing /usr/lib/purple-2/idle.so
(12:27:47) plugins: probing /usr/lib/purple-2/buddynote.so
(12:27:47) plugins: probing /usr/lib/purple-2/libnovell.so
(12:27:47) plugins: probing /usr/lib/purple-2/perl.so
(12:27:47) plugins: probing /usr/lib/purple-2/ssl-nss.so
(12:27:47) plugins: probing /usr/lib/purple-2/joinpart.so
(12:27:47) plugins: probing /usr/lib/purple-2/nss-prefs.so
(12:27:47) plugins: probing /usr/lib/purple-2/autoaccept.so
(12:27:47) plugins: probing /usr/lib/purple-2/tcl.so
(12:27:47) plugins: probing /usr/lib/purple-2/libjabber.so
(12:27:47) plugins: /usr/lib/purple-2/libjabber.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(12:27:47) plugins: probing /usr/lib/purple-2/statenotify.so
(12:27:47) plugins: probing /usr/lib/purple-2/libzephyr.so
(12:27:47) plugins: probing /usr/lib/purple-2/liboscar.so
(12:27:47) plugins: /usr/lib/purple-2/liboscar.so is not usable because the 'purple_init_plugin' symbol could not be found.  Does the plugin call the PURPLE_INIT_PLUGIN() macro?
(12:27:47) plugins: probing /usr/lib/purple-2/offlinemsg.so
(12:27:47) plugins: probing /usr/lib/purple-2/log_reader.so
(12:27:47) plugins: probing /usr/lib/purple-2/libicq.so
(12:27:47) plugins: probing /usr/lib/purple-2/libxmpp.so
(12:27:47) gg: Loading Gadu-Gadu protocol plugin with libgadu 1.12.2...
(12:27:47) mediamanager: Registered Audio/Source device Built-in Audio Analog Stereo
(12:27:47) mediamanager: Registered Audio/Sink device Built-in Audio Analog Stereo
(12:27:47) mediamanager: Registered Video/Source device USB2.0 HD UVC WebCam: USB2.0 HD
(12:27:47) util: Reading file xmpp-caps.xml from directory /home/marcus/.purple
(12:27:47) util: File /home/marcus/.purple/xmpp-caps.xml does not exist (this is not necessarily an error)
(12:27:47) jabber: creating hash tables for data objects
(12:27:47) prefs: /purple/status/scores/offline changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/available changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/invisible changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/away changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/extended_away changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/idle changed, scheduling save.
(12:27:47) prefs: /purple/status/scores/offline_msg changed, scheduling save.
(12:27:47) util: Reading file accounts.xml from directory /home/marcus/.purple
(12:27:47) util: File /home/marcus/.purple/accounts.xml does not exist (this is not necessarily an error)
(12:27:47) util: Reading file status.xml from directory /home/marcus/.purple
(12:27:47) certificate: CertificateVerifier x509, singleuse requested but not found.
(12:27:47) certificate: CertificateVerifier singleuse registered
(12:27:47) certificate: CertificatePool x509, ca requested but not found.
(12:27:47) certificate: CertificateScheme x509 requested but not found.
(12:27:47) certificate/x509/ca: Lazy init failed because an X.509 Scheme is not yet registered. Maybe it will be better later.
(12:27:47) certificate/x509/ca: Init failed, probably because a dependency is not yet registered. It has been deferred to later.
(12:27:47) certificate: CertificatePool ca registered
(12:27:47) certificate: CertificatePool x509, tls_peers requested but not found.
(12:27:47) certificate: CertificatePool tls_peers registered
(12:27:47) certificate: CertificateVerifier x509, tls_cached requested but not found.
(12:27:47) certificate: CertificateVerifier tls_cached registered
(12:27:47) prefs: /purple/logging/format changed, scheduling save.
(12:27:47) prefs: /purple/logging/format changed, scheduling save.
(12:27:47) prefs: /purple/proxy/type changed, scheduling save.
(12:27:47) prefs: /purple/proxy/host changed, scheduling save.
(12:27:47) prefs: /purple/proxy/port changed, scheduling save.
(12:27:47) prefs: /purple/proxy/username changed, scheduling save.
(12:27:47) prefs: /purple/proxy/password changed, scheduling save.
(12:27:47) nss: Cipher - TLS_AES_128_GCM_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_CHACHA20_POLY1305_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_AES_256_GCM_SHA384: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_RC4_128_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_GCM_SHA256: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_GCM_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_128_CBC_SHA256: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_AES_256_CBC_SHA256: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_RC4_128_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_ECDSA_WITH_RC4_128_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_RSA_WITH_RC4_128_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_128_GCM_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_256_GCM_SHA384: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_128_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_128_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_CAMELLIA_128_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_256_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_AES_256_CBC_SHA256: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_CAMELLIA_256_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_SEED_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_3DES_EDE_CBC_SHA: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_RC4_128_SHA: Enabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_RC4_128_MD5: Enabled
(12:27:47) nss: Cipher - TLS_DHE_RSA_WITH_DES_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_DHE_DSS_WITH_DES_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_DES_CBC_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_ECDSA_WITH_NULL_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDHE_RSA_WITH_NULL_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_RSA_WITH_NULL_SHA: Disabled
(12:27:47) nss: Cipher - TLS_ECDH_ECDSA_WITH_NULL_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_NULL_SHA: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_NULL_SHA256: Disabled
(12:27:47) nss: Cipher - TLS_RSA_WITH_NULL_MD5: Disabled
(12:27:47) nss: TLS supported versions: 0x0301 through 0x0304
(12:27:47) nss: TLS versions allowed by default: 0x0301 through 0x0303
(12:27:47) certificate: CertificateScheme x509 requested but not found.
(12:27:47) certificate: CertificateScheme x509 registered
(12:27:47) util: Reading file smileys.xml from directory /home/marcus/.purple
(12:27:47) util: File /home/marcus/.purple/smileys.xml does not exist (this is not necessarily an error)
(12:27:47) stun: using server 
(12:27:48) sound: Initializing sound output drivers.
(12:27:48) prefs: /pidgin/conversations/placement changed, scheduling save.
(12:27:48) prefs: purple_prefs_get_bool: Unknown pref /pidgin/docklet/x11/embedded
(12:27:48) GLib-GObject: ../../../../gobject/gsignal.c:2523: signal 'destroy' is invalid for instance '0x563796fd8b40' of type 'GtkStatusIcon'
(12:27:48) gtkblist: added visibility manager: 1
(12:27:48) docklet: GTK+ created
(12:27:48) gtkmedia: Registering media element types
(12:27:48) util: Reading file blist.xml from directory /home/marcus/.purple
(12:27:48) util: File /home/marcus/.purple/blist.xml does not exist (this is not necessarily an error)
(12:27:48) pounce: Error reading pounces: Failed to open file “/home/marcus/.purple/pounces.xml”: No such file or directory
(12:27:48) Session Management: ICE initialized.
(12:27:48) Session Management: Connecting with no previous ID
(12:27:48) Session Management: Handling new ICE connection... 
(12:27:48) done.
(12:27:48) Session Management: Connected to manager (gnome-session) with client ID 10f6c8f94d3d3dd35615858448685110000000038080076
(12:27:48) Session Management: Using pidgin as command
(12:27:48) GLib-GObject: value "-1779789431" of type 'gint' is invalid or out of range for property 'weight' of type 'gint'
(12:27:48) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file : Failed to open file '': No such file or directory
(12:27:48) util: requesting to fetch a URL
(12:27:48) dnsquery: Performing DNS lookup for 10.0.0.1
(12:27:48) Session Management: Received first save_yourself
(12:27:48) Session Management: Received save_complete
(12:27:48) dnsquery: IP resolved for 10.0.0.1
(12:27:48) proxy: Attempting connection to 10.0.0.1
(12:27:48) proxy: Connecting to 10.0.0.1:49152 with no proxy
(12:27:48) proxy: Connection in progress
(12:27:48) proxy: Connecting to 10.0.0.1:49152.
(12:27:48) proxy: Connected to 10.0.0.1:49152.
(12:27:48) util: request constructed
(12:27:48) util: Response headers: 'HTTP/1.1 200 OK
CONTENT-LENGTH: 2932
CONTENT-TYPE: text/xml
DATE: Thu, 02 Apr 2020 16:24:46 GMT
LAST-MODIFIED: Tue, 31 Mar 2020 11:19:53 GMT
SERVER: Linux/3.12.14, UPnP/1.0, Portable SDK for UPnP devices/1.6.22
X-User-Agent: redsonic
CONNECTION: close

'
(12:27:48) util: parsed 2932
(12:27:48) util: requesting to fetch a URL
(12:27:48) dnsquery: Performing DNS lookup for 10.0.0.1
(12:27:48) dnsquery: Performing DNS lookup for 10.0.0.1
(12:27:48) dnsquery: IP resolved for 10.0.0.1
(12:27:48) proxy: Attempting connection to 10.0.0.1
(12:27:48) proxy: Connecting to 10.0.0.1:49152 with no proxy
(12:27:48) proxy: Connection in progress
(12:27:48) dnsquery: IP resolved for 10.0.0.1
(12:27:48) proxy: Attempting connection to 10.0.0.1
(12:27:48) proxy: Connecting to 10.0.0.1:49152 with no proxy
(12:27:48) proxy: Connection in progress
(12:27:48) proxy: Connecting to 10.0.0.1:49152.
(12:27:48) proxy: Connected to 10.0.0.1:49152.
(12:27:48) util: request constructed
(12:27:48) proxy: Connecting to 10.0.0.1:49152.
(12:27:48) proxy: Connected to 10.0.0.1:49152.
(12:27:48) upnp: Local IP: 10.0.0.4
(12:27:48) util: Response headers: 'HTTP/1.1 200 OK
CONTENT-LENGTH: 342
CONTENT-TYPE: text/xml; charset="utf-8"
DATE: Thu, 02 Apr 2020 16:24:46 GMT
EXT:
SERVER: Linux/3.12.14, UPnP/1.0, Portable SDK for UPnP devices/1.6.22
X-User-Agent: redsonic

'
(12:27:48) util: parsed 342
(12:27:48) upnp: NAT Returned IP: 68.54.125.248
(12:27:53) util: Writing file prefs.xml to directory /home/marcus/.purple
(12:27:53) util: Writing file /home/marcus/.purple/prefs.xml
(12:27:53) docklet: failed to embed within timeout
(12:27:53) gtkblist: removed visibility manager: 0
`
Hey, thanks for the help, by the way! You're awesome!

**Comment by dwmw2** [comment]
Compare with mine, which goes...

(08:02:35) plugins: probing /usr/lib/purple-2/libsametime.so
(08:02:35) plugins: /usr/lib/purple-2/libsametime.so has a prefs_info, but is a prpl. This is no longer supported.
**(08:02:35) plugins: probing /usr/lib/purple-2/libchimeprpl.so**
(08:02:35) plugins: probing /usr/lib/purple-2/dbus-example.so
(08:02:35) plugins: probing /usr/lib/purple-2/log_reader.so

When you say you installed it... does it really exist in /usr/lib/purple-2 ?

**Comment by MarcusRhodes** [comment]
It doesn't seem to be in that directory, so I tried installing pidgin itself as `sudo apt install pidgin-chime`, and it worked! Thanks for you help, dwmw2!

**Comment by dwmw2** [comment]
Do `apt-get update; apt-get upgrade` too and you will probably get a newer version of pidgin itself with some useful fixes that went into 2.13.

**Comment by MarcusRhodes** [comment]
Sorry to bother you again, but I can't seem to login to my Amazon Chime account. Every time I try, it just prompts again. I tried installing the latest version of pidgin, but I got `pidgin is already the newest version (1:2.14.0dev-5~bionic1).
` Is there something wrong I'm doing?

**Comment by dwmw2** [comment]
In the account config you enter your full @amazon email address. When it tries to connect it will give a login prompt at which you enter only your username, no @amazon.

If that's what you're doing and it still doesn't work please run:
 $ script pidgin-auth.log
 $ CHIME_DEBUG=1 pidgin -d

Let it fail, quit pidgin and then
 $ exit

Then edit your password (your normal domain password) out of the resulting pidgin-auth.log file and mail it to me.

On 2 April 2020 23:28:52 BST, MarcusRhodes <notifications@github.com> wrote:
>Sorry to bother you again, but I can't seem to login to my Amazon Chime
>account. Every time I try, it just prompts again. I tried installing
>the latest version of pidgin, but I got `pidgin is already the newest
>version (1:2.14.0dev-5~bionic1).
>` Is there something wrong I'm doing?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/awslabs/pidgin-chime/issues/46#issuecomment-608124408

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
