### ISSUE TITLE
Ubuntu 20.04 - Screen share doesn't resize anymore

### ISSUE THREAD

**Issue by ahmetipkin** [awslabs/pidgin-chime#48]
Pidgin version:  2.14.0devel 
plugin version: pidgin-chime 1.3
OS: Ubuntu 20.04 - kernel 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
WM : XFCE 4.14

When someone shares their screen with me; I cannot resize the window to make it bigger anymore. This used to work just fine under 18.04.. I don't know what changed :)

**Comment by dwmw2** [comment]
In the voice and video preferences what is your output video device set to in each case?

**Comment by ahmetipkin** [comment]
It was 'Default'. Should I switch?

**Comment by ahmetipkin** [comment]
Yes; it was the issue! When I picked 'X Video System' it started scaling! :)
